### PR TITLE
Merge multiple forks

### PR DESCRIPTION
**Pull request by ToddGreenfield**
PR/merge from @mattvj and @dstapleton92 master branches. 
Tested and working.
Addresses #19, #17, #16 which can be closed out once merged.
Will also request a PR/merge of Matt's local nodealarmproxy to martzcodes/master.
Once that is completed all should be up to speed.
TODO- bump version and update readme.

### CODE REVIEW

**Review by dustindclark — APPROVED** [review]
Thanks for the contribution!!

**Comment by IMNotMax** [comment]
Hi, First thank you for the update !!!! But just to inform you:

`pi@RaspberryPi3:~ $ sudo npm install -g homebridge-envisalink
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/mattvj/NodeAlarmProxy.git /root/.npm/_cacache/tmp/git-clone-c41de8d5
npm ERR! fatal: impossible de créer les répertoires de premier niveau dans '/root/.npm/_cacache/tmp/git-clone-c41de8d5': Permission non accordée
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-25T01_30_33_945Z-debug.log`


Here the log file : https://www.dropbox.com/s/u7a9yzkpnc4mfhv/2017-10-25T01_30_33_945Z-debug.log?dl=0
(the French error: not allowed to create first level directories in '/root/.npm/_cacache/tmp/git-clone-c41de8d5')

My "old version 0.1.6" is still working

**Comment by dstapleton92** [comment]
Hi @IMNotMax. I’ve actually encountered that issue before. It has to do with npm installing packages via git instead of the usual way. I was able to fix it by following this guide to fix my npm permissions: [https://docs.npmjs.com/getting-started/fixing-npm-permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions)

Note that following those steps will change the folder where your global node modules are stored, so you will probably need to npm install homebridge and npm install your other plugins again as well. Note that after following that guide, you will not use “sudo” in front of the npm commands. 

Also, if you have set up your raspberry pi to automatically start homebridge on bootup, you’ll need to make changes there as well. 

I’m sure there is another way, but this is one method I know works.

**Comment by IMNotMax** [comment]
Thanx ! I'll check this !

> EDIT: changing permissions works!

**Comment by IMNotMax** [comment]
Ok, I'm now able to install the 0.2.0 version.... but:
```
0|homebrid | [2017-10-24 22:04:02] [Envisalink] Node alarm proxy started.  Listening for connections at: 0.0.0.0:4026
0|homebrid | TypeError: Cannot read property 'length' of undefined
0|homebrid |     at new EnvisalinkPlatform (/usr/local/lib/node_modules/homebridge-envisalink/index.js:85:42)
0|homebrid |     at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:294:32)
0|homebrid |     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
0|homebrid |     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
0|homebrid |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
0|homebrid |     at Module._compile (module.js:573:30)
0|homebrid |     at Object.Module._extensions..js (module.js:584:10)
0|homebrid |     at Module.load (module.js:507:32)
0|homebrid |     at tryModuleLoad (module.js:470:12)
0|homebrid |     at Function.Module._load (module.js:462:3)
0|homebrid |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:70:21)
0|homebrid |     at Module._compile (module.js:573:30)
0|homebrid |     at Object.Module._extensions..js (module.js:584:10)
0|homebrid |     at Module.load (module.js:507:32)
0|homebrid |     at tryModuleLoad (module.js:470:12)
0|homebrid |     at Function.Module._load (module.js:462:3)
```

Back to 0.1.6 :(
Thanx for your help if you have any idea !

**Comment by dstapleton92** [comment]
Hi @IMNotMax   This version of the plugin supports user programs and requires an array be defined in config.json (see the readme). If you don’t have user programs or don’t want to support them, you will still need `”userPrograms”: []` (normal double quotes, not fancy quotes)

**Comment by ToddGreenfield** [comment]
Apologies all. I probably should have added a little note to the readme explaining that an array is needed, even if empty. Once we get the nodealarmproxy PR merged someone can update the package.json and readme as well.

**Comment by IMNotMax** [comment]
Thanx ! Everything works with the 0.2.0 now !
Because I'm curious, what these user programs are ?

**Comment by SirNoble** [comment]
Hi, 
Is there any easy way to updating this? (I.e sudo npm update homebridge-envisalink)
Don't really want to install on plugins/homebridge again.

**Comment by ToddGreenfield** [comment]
Just reinstall the plugin the same way you installed it originally. Probably need to use the -g flag to install globally.

npm install -g homebridge-envisalink

**Comment by SirNoble** [comment]
@ToddGreenfield 
I get the same error as above when installing:
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/mattvj/NodeAlarmProxy.git /root/.npm/_cacache/tmp/git-clone-c28d6b2a
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-c28d6b2a': Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-26T02_23_12_656Z-debug.log

**Comment by dstapleton92** [comment]
@SirNoble I haven’t tested this to be sure, but something you could try is to open a super user shell. So do `sudo su` and then do `npm install -g homebridge-envisalink`  If it succeeds, remember to type `exit` to quit the super user shell. 

Not sure if there are any consequences to doing this. Any thoughts anyone?

The alternative is to wait until Node alarm proxy gets updated and pushed to npm, then this project can reference it as a normal npm dependency instead of via git.

**Comment by IMNotMax** [comment]
Here the steps I made thanx to @dstapleton92:
1/ sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share} to modify the permissions on the folders used by npm 

2/ add the “userPrograms”:[ ] in the confit.json

3/ npm install -g homebridge-envisalink (without the sudo, now you own the directories !)

Hope this helps !

**Comment by dstapleton92** [comment]
Make sure you follow the steps at the link I posted above if fixing npm permissions. Some configurations require “option 2” at the link. Following option 1 mentioned above can cause issues on those systems.

**Comment by SirNoble** [comment]
@IMNotMax 
Yes, that worked!
Thank you!

**Comment by ToddGreenfield** [comment]
@IMNotMax @SirNoble  I use option 2 in the above link and it works well. @dstapleton92 I also had to upgrade to node v7.x. Apparently Object.values (line 252) isn't supported in node <v7.  It was either upgrade or change the code to use _underscore... When the readme is updated will need to also make a note about the node version requirement... thanks again for your work on this.

**Pull request merged**
